'''
barcoded stacked bar plot generator - v1.0
###################################################################################################
#####################################    About this script    #####################################
###################################################################################################

This script is designed to take the output files from barcodeID.py and generate custom stacked bar
plots using a graphical user interface. 

The only file that this script specifically requires is the "all_barcode_freq.table.txt" in the 
"barcode_info" folder. But, it will also attempt to fine the following files:
 - "sample_titers.txt" so the bar heights can be scaled to titer. If not found, heights will 
    scale to 1.0
 - "barcode_color_map.txt" - this file is generated by barcodeID to maximize color differences
    between the highest frequency barcodes. If not found, an arbitrary color scheme will be used

########################################    Requirements    #######################################
python3
the following python modules:
 - tkinter (tk)
 - matplotlib
 - pandas
 - seaborn
 - numpy

For any questions, please contact the author of this script, Dave VanInsberghe, through the Lowen Lab
GitHub, or directly via dvanins@emory.edu.
If you find this script helpful, please cite the original publication to which it was published.

###################################################################################################
###################################   HOW TO RUN THIS SCRIPT    ###################################
###################################################################################################

Copy files from computing server to your computer, then run it in terminal generate bar plots using
a graphical user interface.

 - Add as many rows and columns as you would like, then paste the names of samples in the order that
   you would like them plotted into the text boxes. Like this:

		sample1
		sample2
		sample3

 - If you would like to have them labeled in the plot as something other than the full sample name,
   add label next to each sample ID, separated by a tab (This format is used to make it easier to 
   copy/paste from an excel sheet), like this:

		sample1	d1
		sample2	d2
		sample3	d3

Under filename, enter a filename that ends with .pdf, .svg, .png, .tif, or .jpeg
  - Image formats will be exported with a resolution of 600dpi

###################################################################################################
#######################################    UPDATE NOTES    ########################################
###################################################################################################

'''
###################################### Load required modules ######################################
import os
import sys
import math
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import tkinter as tk
from tkinter import *
from tkinter import ttk
from functools import partial
###################################### Establish variables #######################################
project_dir = "./"
barcode_color_filename = 'barcode_color_map.txt'
freq_file_path = './barcode_info/all_barcode_freq.table.txt'
titer_filename = 'sample_titers.txt'
############################################ FUNCTIONS ############################################
class DynamicGridApp:
	def __init__(self, root):
		self.root = root
		self.root.title("Dynamic Textbox Grid")
		self.rows = 1
		self.cols = 1
		self.textboxes = []
		self.submitted_data = None
		# -------- Top Input --------
		input_frame = tk.Frame(root)
		input_frame.pack(pady=5)

		tk.Label(input_frame, text="Filename:").pack(side="left")
		self.user_input = tk.Entry(input_frame, width=40)
		self.user_input.pack(side="left", padx=5)
		# -------- Grid Frame --------
		self.grid_frame = tk.Frame(root)
		self.grid_frame.pack(fill="both", expand=True, padx=10, pady=10)
		# -------- Control Buttons --------
		control_frame = tk.Frame(root)
		control_frame.pack(pady=5)
		tk.Button(control_frame, text="Add Row", command=self.add_row).grid(row=0, column=0, padx=5)
		tk.Button(control_frame, text="Remove Row", command=self.remove_row).grid(row=0, column=1, padx=5)
		tk.Button(control_frame, text="Add Column", command=self.add_column).grid(row=0, column=2, padx=5)
		tk.Button(control_frame, text="Remove Column", command=self.remove_column).grid(row=0, column=3, padx=5)
		tk.Button(control_frame, text="Submit", command=self.submit).grid(row=0, column=4, padx=10)
		self.create_grid()
	def create_textbox(self, row, col):
		frame = tk.Frame(self.grid_frame)
		frame.grid(row=row, column=col, sticky="nsew", padx=3, pady=3)
		text = tk.Text(frame, width=15, height=2, wrap="none")
		text.pack(side="left", fill="both", expand=True)
		scrollbar = tk.Scrollbar(frame, command=text.yview)
		scrollbar.pack(side="right", fill="y")
		text.config(yscrollcommand=scrollbar.set)
		return text
	def create_grid(self):
		self.textboxes = []
		for r in range(self.rows):
			row = []
			for c in range(self.cols):
				txt = self.create_textbox(r, c)
				row.append(txt)
			self.textboxes.append(row)
		self.update_grid_weights()
	def update_grid_weights(self):
		for r in range(self.rows):
			self.grid_frame.rowconfigure(r, weight=1)
		for c in range(self.cols):
			self.grid_frame.columnconfigure(c, weight=1)
	def add_row(self):
		row = []
		for c in range(self.cols):
			txt = self.create_textbox(self.rows, c)
			row.append(txt)
		self.textboxes.append(row)
		self.rows += 1
		self.update_grid_weights()
	def remove_row(self):
		if self.rows > 1:
			for widget in self.textboxes[-1]:
				widget.master.destroy()
			self.textboxes.pop()
			self.rows -= 1
	def add_column(self):
		for r in range(self.rows):
			txt = self.create_textbox(r, self.cols)
			self.textboxes[r].append(txt)
		self.cols += 1
		self.update_grid_weights()
	def remove_column(self):
		if self.cols > 1:
			for r in range(self.rows):
				widget = self.textboxes[r][-1]
				widget.master.destroy()
				self.textboxes[r].pop()
			self.cols -= 1
	def submit(self):
		grid_data = {}
		for r in range(self.rows):
			for c in range(self.cols):
				content = self.textboxes[r][c].get("1.0", "end-1c")
				grid_data[(r, c)] = content
		self.submitted_data = {
			"filename": self.user_input.get(),
			"grid": grid_data
		}
		self.root.withdraw()
		self.root.quit()

def run_grid_input():
	root = tk.Tk()
	app = DynamicGridApp(root)
	root.mainloop()
	return app.submitted_data

###################################################################################################
### Pull titer values and store in a dictionary
titer_dict = {}
titer_file_found = False
if os.path.isfile(titer_filename):
	titer_file_found = True
	infile = open(titer_filename,"r")
	first_line = True
	for line in infile:
		line = line.strip()
		if len(line) >0:
			if line[0]!='#':
				line = line.split("\t")
				sampleID = line[0]
				try:
					titer = float(line[1])
				except:
					titer = 0
				if titer == 0 and first_line == True:
					first_line = False
				elif titer == 0 and first_line == False:
					titer_dict[sampleID] = titer
				else:
					titer_dict[sampleID] = titer
				if first_line == True:
					first_line = False
			else:
				first_line = False
	infile.close()
else:
	print('No titer files provided. Scaling bars to 1.0')

input_info_dict = run_grid_input()
output_filename = input_info_dict['filename']
input_info_dict = input_info_dict['grid']

max_titer = 1.
plot_order_dict = {}
input_sampleID_list = {}
missing_titers = {}

for entry in input_info_dict:

	row,col = entry[0],entry[1]
	sample_label_list = input_info_dict[entry].replace('\r','').split('\n')
	local_sample_list = []
	local_label_list = []
	for s in range(0,len(sample_label_list)):
		sample_label = sample_label_list[s].split('\t')
		if len(sample_label) == 1:
			sampleID = sample_label[0].strip()
			labelID = sampleID
		elif len(sample_label) == 2:
			sampleID = sample_label[0].strip()
			labelID = sample_label[1].strip()
		else:
			sys.exit("Too many values entered. Max 2 columns per text box. Exiting.")
		if sampleID != '':
			try:
				labelID = int(labelID)
			except:
				pass
			local_sample_list.append(sampleID)
			local_label_list.append(labelID)
			input_sampleID_list[sampleID] = 0
			try:
				titer = titer_dict[sampleID]
			except:
				titer = 0.
			if titer > max_titer:
				max_titer = titer
	try:
		plot_order_dict[row][col] = (tuple(local_sample_list),tuple(local_label_list))
	except:
		plot_order_dict[row] = {}
		plot_order_dict[row][col] = (tuple(local_sample_list),tuple(local_label_list))


#### Load frequency of barcodes in samples
barcode_freq_dict = {}
barcode_list = {}
freq_infile = open(freq_file_path,"r")
first_line = True
for line in freq_infile:
	line = line.strip().split("\t")
	if first_line == True:
		sample_list = line
		first_line = False
	else:
		barcodeID = line[0]
		barcode_list[barcodeID] = ''
		for number in range(1,len(line)):
			freq = float(line[number])
			sampleID = sample_list[number-1]
			include_sample = False
			try:
				input_sampleID_list[sampleID]
				include_sample = True
			except:
				include_sample = False
			if include_sample == True:
				try:
					barcode_freq_dict[sampleID][barcodeID] = freq
				except:
					barcode_freq_dict[sampleID] = {}
					barcode_freq_dict[sampleID][barcodeID] = freq
				input_sampleID_list[sampleID] = 1
freq_infile.close()
barcode_list = list(barcode_list.keys())
freq_samples = list(barcode_freq_dict.keys())

### Load barcode color values
colorblind_friendly_palette = ['#E8ECFB', '#D9CCE3', '#D1BBD7', '#CAACCB', '#BA8DB4', '#AE76A3', '#AA6F9E', '#994F88', '#882E72', '#1965B0', '#437DBF', '#5289C7', '#6195CF', '#7BAFDE', '#4EB265', '#90C987', '#CAE0AB', '#F7F056', '#F7CB45', '#F6C141', '#F4A736', '#F1932D', '#EE8026', '#E8601C', '#E65518', '#DC050C', '#A5170E', '#72190E', '#42150A']
barcode_color_dict = {}
if os.path.isfile(barcode_color_filename):
	infile = open(barcode_color_filename,'r')
	for line in infile:
		line = line.strip().split("\t")
		barcodeID = line[0]
		hex_val = line[1]
		barcode_color_dict[barcodeID] = hex_val
	infile.close()
else:
	print('No barcode color map file provided. Using alphabetical order of barcodes to generate one.')
	for num in range(0,len(barcode_list)):
		barcodeID = barcode_list[num]
		color_index = num%len(colorblind_friendly_palette)
		color_hex_value = colorblind_friendly_palette[color_index]
		barcode_color_dict[barcodeID] = color_hex_value

### make titer scaled frequencies for stacked bar plots
no_titer_found = {}
adjust_barcode_freq_dict = {}
for sampleID in barcode_freq_dict:
	try:
		titer = titer_dict[sampleID]
	except:
		titer = 1.
		no_titer_found[sampleID] = ''
	adjust_barcode_freq_dict[sampleID] = {}
	for barcodeID in barcode_freq_dict[sampleID]:
		freq = barcode_freq_dict[sampleID][barcodeID]
		adjusted_freq = freq*titer
		adjust_barcode_freq_dict[sampleID][barcodeID] = adjusted_freq
if len(no_titer_found)>0 and titer_file_found==True:
	print(str(len(no_titer_found))+' samples did not have a linked titer value:')
	for sampleID in no_titer_found:
		print(sampleID)

samples_not_found = []
for sampleID in input_sampleID_list:
	if input_sampleID_list[sampleID] == 0:
		samples_not_found.append(sampleID)
if len(samples_not_found)>0:
	print('The following samples were not found in the frequency input file:')
	for s in range(0,len(samples_not_found)):
		print(samples_not_found[s])

def organize_barcodes_to_plot_reduce_invisible_complexity(sample_list,barcode_freq_dict,barcode_list,barcode_color_dict):
	min_visible_freq = 5e-4
	freq_dict_temp = {}
	freq_dict_out = {}
	barcode_list_out = []
	barcode_colors_out = []
	
	num_above_0 = 0
	num_collapsed = 0
	
	current_barcode_sink = ''
	collapse_dict = {}
	running_barcode_sum_dict = {}

	for b in range(0,len(barcode_list)):
		barcodeID = barcode_list[b]
		include = False
		over_min_visible_freq = False

		for s in range(0,len(sample_list)):
			sampleID = sample_list[s]
			try:
				freq = barcode_freq_dict[sampleID][barcodeID]
				if freq >0.:
					include = True
					if freq > min_visible_freq:
						over_min_visible_freq = True
			except:
				pass
		if include == True:
			num_above_0 += 1
			if over_min_visible_freq == True:
				collapse_dict[barcodeID] = [barcodeID]
				for sampleID in barcode_freq_dict:
					running_barcode_sum_dict[sampleID] = 0
					current_barcode_sink = ''
			else:
				if current_barcode_sink == '':
					current_barcode_sink = barcodeID
					collapse_dict[barcodeID] = [barcodeID]
					for sampleID in barcode_freq_dict:
						running_barcode_sum_dict[sampleID] = barcode_freq_dict[sampleID][barcodeID]
				else:
					can_collapse_next = True
					for sampleID in barcode_freq_dict:
						new_freq = running_barcode_sum_dict[sampleID]+barcode_freq_dict[sampleID][barcodeID]
						if new_freq > min_visible_freq:
							can_collapse_next = False
					if can_collapse_next == False:
						current_barcode_sink = barcodeID
						collapse_dict[barcodeID] = [barcodeID]
						for sampleID in barcode_freq_dict:
							running_barcode_sum_dict[sampleID] = barcode_freq_dict[sampleID][barcodeID]
					else:
						num_collapsed +=1
						collapse_dict[current_barcode_sink].append(barcodeID)
						for sampleID in barcode_freq_dict:
							running_barcode_sum_dict[sampleID] += barcode_freq_dict[sampleID][barcodeID]
	collapse_freq_dict = {}
	for s in range(0,len(sample_list)):
		sampleID = sample_list[s]
		collapse_freq_dict[sampleID] = {}
		for barcode_sink in collapse_dict:
			# barcode_color = barcode_color_dict[barcode_sink]
			for barcodeID in collapse_dict[barcode_sink]:
				try:
					collapse_freq_dict[sampleID][barcode_sink] += barcode_freq_dict[sampleID][barcodeID]
				except:
					try:
						collapse_freq_dict[sampleID][barcode_sink] = barcode_freq_dict[sampleID][barcodeID]
					except:
						collapse_freq_dict[sampleID][barcode_sink] = 0.
	for b in range(0,len(barcode_list)):
		barcodeID = barcode_list[b]
		try:
			collapse_dict[barcodeID]
			barcode_list_out.append(barcodeID)
			barcode_colors_out.append(barcode_color_dict[barcodeID])
		except:
			pass
	for s in range(0,len(sample_list)):
		sampleID = sample_list[s]
		freq_dict_out[sampleID] = []
		for b in range(0,len(barcode_list_out)):
			barcodeID = barcode_list_out[b]
			collapse_freq = collapse_freq_dict[sampleID][barcodeID]
			freq_dict_out[sampleID].append(collapse_freq)
	return freq_dict_out,barcode_list_out,barcode_colors_out
def organize_barcodes_to_plot(sample_list,barcode_freq_dict,barcode_list,barcode_color_dict):
	freq_dict_out = {}
	barcode_list_out = []
	barcode_colors_out = []

	for b in range(0,len(barcode_list)):
		barcodeID = barcode_list[b]
		include = False
		for s in range(0,len(sample_list)):
			sampleID = sample_list[s]
			try:
				freq = barcode_freq_dict[sampleID][barcodeID]
				if freq >0.:
					include = True
			except:
				pass
		if include == True:
			barcode_color = barcode_color_dict[barcodeID]
			barcode_list_out.append(barcodeID)
			barcode_colors_out.append(barcode_color)
			for s in range(0,len(sample_list)):
				sampleID = sample_list[s]
				try:
					freq = barcode_freq_dict[sampleID][barcodeID]
				except:
					freq = 0.0
				try:
					freq_dict_out[sampleID].append(freq)
				except:
					freq_dict_out[sampleID] = [freq]
	return freq_dict_out,barcode_list_out,barcode_colors_out


row_list = list(plot_order_dict.keys())
num_rows = len(row_list)
max_bars_per_col = 0
max_cols_per_row = 0
for row in plot_order_dict:
	local_cols = len(plot_order_dict[row])
	if local_cols > max_cols_per_row:
		max_cols_per_row = local_cols
	for col in plot_order_dict[row]:
		num_bars = len(plot_order_dict[row][col][0])
		if num_bars > max_bars_per_col:
			max_bars_per_col = num_bars
width_per_bar = 0.4

page_width = max(2.,max_cols_per_row*max_bars_per_col*width_per_bar)
fig, axs = plt.subplots(num_rows, max_cols_per_row,sharex=False, sharey=True)
fig.set_size_inches(page_width, num_rows*3.5)

for row in range(0,num_rows):
	for col in range(0,max_cols_per_row):
		if num_rows >1 and max_cols_per_row >1:
			row_col = axs[row, col]
		elif num_rows == 1 and max_cols_per_row >1:
			row_col = axs[col]
		elif num_rows > 1 and max_cols_per_row ==1:
			row_col = axs[row]
		elif num_rows == 1 and max_cols_per_row ==1:
			row_col = axs

		try:
			local_sample_list = plot_order_dict[row][col][0]
			local_label_list = plot_order_dict[row][col][1]
			if local_sample_list == ():
				row_col.axis('off')
		except:
			row_col.axis('off')
			local_sample_list = ''
			local_label_list = ''

		if local_sample_list != '':
			local_barcode_dict,local_barcode_list,local_color_list = organize_barcodes_to_plot_reduce_invisible_complexity(local_sample_list,adjust_barcode_freq_dict,barcode_list,barcode_color_dict)
			# local_barcode_dict,local_barcode_list,local_color_list = organize_barcodes_to_plot(local_sample_list,adjust_barcode_freq_dict,barcode_list,barcode_color_dict)
			df_key = ['samples']
			df_key.extend(local_barcode_list)
			plot_barcode_array = []
			for s in range(0,len(local_sample_list)):
				sampleID = local_sample_list[s]
				titer_freq_array = [sampleID]
				titer_freq_array.extend(local_barcode_dict[sampleID])
				plot_barcode_array.append(titer_freq_array)
			if len(plot_barcode_array)>0:
				barcode_df = pd.DataFrame(plot_barcode_array,columns=df_key)
				titer_freq_bar_plot = barcode_df.plot(x='samples', kind='bar', stacked=True,legend=False,color=local_color_list,ax=row_col,width=0.94,ylim=(0, max_titer*1.05))#,ylabel="Titer",title=title_string,
				if col == 0:
					if titer_file_found==False:
						titer_freq_bar_plot.set_ylabel("Barcode frequency")
					else:
						titer_freq_bar_plot.set_ylabel("Viral titer")
				titer_freq_bar_plot.set_xlabel('')

				titer_freq_bar_plot.set_xticks(range(0,max_bars_per_col))
				if len(local_sample_list)<max_bars_per_col:
					tick_list = list(local_label_list)
					for z in range(0,max_bars_per_col-len(local_sample_list)):
						tick_list.append('')
				else:
					tick_list = list(local_label_list)
				titer_freq_bar_plot.set_xticklabels(tick_list)
plt.tight_layout()
# plt.show()

output_filename = output_filename.replace('/','_')
output_filename = output_filename.replace(' ','_')

if '.pdf' in output_filename or '.svg' in output_filename or '.PDF' in output_filename or '.SVG' in output_filename:
	plt.savefig(output_filename)
elif '.png' in output_filename or '.PNG' in output_filename or '.jpeg' in output_filename or '.JPEG' in output_filename or '.tif' in output_filename or '.TIF' in output_filename:
	plt.savefig(output_filename, dpi=600)
else:
	plt.savefig(output_filename+'.pdf')
